sequenceDiagram
  autonumber
  participant Notifications Publisher
  participant Notifications Target

  loop for each notification
    Notifications Publisher ->> Notifications Target: Deliver notification
    Notifications Target ->> Notifications Publisher: 200 OK
  end
