sequenceDiagram
  participant Subscription Client
  participant Resource Server
  participant Subscription Server

  Subscription Client ->> Resource Server: HEAD Resource (topic)
  Resource Server ->> Subscription Client: HTTP Link rel="describedby"
  Subscription Client ->> Resource Server: GET Description Resource
  Resource Server ->> Subscription Client: Description Resource
  Subscription Client ->> Subscription Server: Subscription Request
  Subscription Server ->> Subscription Client: Subscription Response (with Notification Channel)
