sequenceDiagram
  autonumber
  participant Subscriber
  participant Discovery Resource
  participant Subscription Resource

  Subscriber ->> Discovery Resource: Discovery
  Discovery Resource ->> Subscriber: Discovery response
  Subscriber ->> Subscription Resource: Request subscription (with authentication)
  Subscription Resource ->> Subscriber: Subscription response (with subscription information)
