sequenceDiagram
  autonumber
  participant Notifications Sender
  participant Notifications Target

  loop for each notification
    Notifications Sender ->> Notifications Target: Deliver notification
    Notifications Target ->> Notifications Sender: 200 OK
  end
