sequenceDiagram
  autonumber
  participant Subscriber
  participant Discovery Resource
  participant Subscription Resource
  participant Notifications Source

  Subscriber ->> Discovery Resource: Discovery
  Discovery Resource ->> Subscriber: Discovery response
  Subscriber ->> Subscription Resource: Request WebSocketsSubscription2021 (with authentication)
  Subscription Resource ->> Subscriber: Subscription response (with wss: notifications source)
  Subscriber ->> Notifications Source: Establish WebSockets connection
  Notifications Source -->> Subscriber: Stream notifications
